### ISSUE TITLE
a question about classification

### ISSUE THREAD

**Issue by hejun888** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#11]
你好，想问一下，通过你这个网络进行instance segmentation 从而进行分类，和对甲状腺结节处进行crop，然后再送入到一个分类网络，哪个分类的效果好些？

**Comment by WAMAWAMA** [comment]
你好
这个框架不是实例分割，只是语义分割，实例分割可以去试一下maskrcnn，yolact之类的（mmdetection大法好）

**Comment by hejun888** [comment]
你好，想问一下通过这个网络进行语义分割来进行分类，和直接用分类网络来分类哪个会好些呢
