### ISSUE TITLE
请问级联网络是怎么定义的

### ISSUE THREAD

**Issue by yu-Mas** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#12]
大佬你好，感谢你的分享，写的很详细！
关于网络我有点疑惑，stage1和stage2使用的网络都是相同的deeplabv3+efficient吗？是使用同一个网络训练两次最后再将结果做集成吗？
期待您的回复，谢谢。

**Comment by WAMAWAMA** [comment]
你好你好，最近有些忙，抱歉回复这么晚

stage1和2是两个不同的网络，是使用不同输入训练出来的（全图和roi），可以具有相同结构，也可以是不同结构
所以准确的来说，确实是训练了两次，但是注意要用不同的数据（全图和roi），
我训练两级网络的时候，使用了相同的结构（deeplabv3+efficient）
你尝试的话，可以试一下smp这个库最新的resnest+Unet++，应该会有更好的结果

**Comment by yu-Mas** [comment]
谢谢大佬这么详细的回复！
我对这句有点疑惑，**“stage1的输出其实是stage2的输入”**，stage1的输出是预测mask，stage2的输入不是roi吗？
感谢大佬对网络的建议，我回头就尝试下resnest+Unet++。大佬有遇到过训练很难出结果的情况吗？（iou一直很低），但我之前使用smp时就经常遇到，无论是unet还是deeplab等，无论是resnet还是efficienet等，不知道是什么原因。
祝好！

**Comment by WAMAWAMA** [comment]
@yu-Mas 
我的回复有点不准确哈，准确的来说：
stage1输出的mask是用来定位的，mask中结节区域对应的原图会被crop出来输入到stage2，所以stage1的输出其实只是用来粗定位结节的，stage2的输入是crop出来的原图的结节部分，以上部分看流程图应该不难理解

训练很难出结果，这个要看你做的是什么任务了，如果就是这个challenge的数据集，性能其实就差不多这么多了
如果你做的是分割CT、MRI图像的肝脏肿瘤、胰腺肿瘤之类的，或者脂肪之类的，那难度可能会搞一些，需要想一些策略来解决

**Comment by yu-Mas** [comment]
嗯嗯，明白，我也感觉stage2应该是起到refine的作用，为了严谨还是咨询了下大佬。
我这边的网络日常github看不到图，科学上网也没用哈哈哈。
我主要是做病理切片分割，平常有分割的比赛也会打打，主要是看到很多比赛后top方案思路和我的差不多，但我的死活训不出来，所以有点纳闷。大佬说的先调研sota效果这点确实不错。
再次感谢大佬的耐心解答！
