### ISSUE TITLE
Question about DDTI dataset

### ISSUE THREAD

**Issue by qdsclove** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#13]
Hi, I downloaded the original DDTI dataset, which only contains 480 images, but the dataset you processed contains 637 images. I was confused where did you get  extra images? I am looking forward to your reply, thanks. @WAMAWAMA

**Comment by WAMAWAMA** [comment]
thanks for your question，due to some of the images in DDTI contain two windows, we did some processing to split them in two, images with filenames(ID) greater than 10000 are separated images, so the number is greater than the original 480. 
![Uploading image.png…]()

**Comment by qdsclove** [comment]
Thanks for your reply @WAMAWAMA
