### ISSUE TITLE
你好，请问为什么我运行您的代码的时候打印验证集上的那些指标都是0啊，在ubuntu环境下

### ISSUE THREAD

**Issue by sjjdd** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#14]
iou,dice什么的都是0

**Comment by sjjdd** [comment]
我是在ubuntu环境下运行的

**Comment by sjjdd** [comment]
def get_accuracy(SR,GT,threshold=0.5):
    SR = SR.view(-1)
    GT = GT.view(-1)
    SR = SR > threshold
    GT = GT == torch.max(GT)
    corr = torch.sum(SR==GT)
    # tensor_size = SR.size(0)*SR.size(1)*SR.size(2)*SR.size(3)
    acc = float(corr)/float(SR.size(0))

    return acc

def get_sensitivity(SR,GT,threshold=0.5):
    # Sensitivity == Recall
    SR = SR > threshold
    GT = GT == torch.max(GT)

    # TP : True Positive
    # FN : False Negative
    TP = ((SR==1)+(GT==1))==2
    FN = ((SR==0)+(GT==1))==2

    SE = float(torch.sum(TP))/(float(torch.sum(TP+FN)) + 1e-6)     
    
    return SE

def get_specificity(SR,GT,threshold=0.5):
    SR = SR > threshold
    GT = GT == torch.max(GT)

    # TN : True Negative
    # FP : False Positive
    TN = ((SR==0)+(GT==0))==2
    FP = ((SR==1)+(GT==0))==2

    SP = float(torch.sum(TN))/(float(torch.sum(TN+FP)) + 1e-6)
    
    return SP

def get_precision(SR,GT,threshold=0.5):
    SR = SR > threshold
    GT = GT == torch.max(GT)

    # TP : True Positive
    # FP : False Positive
    TP = ((SR==1)+(GT==1))==2
    FP = ((SR==1)+(GT==0))==2

    PC = float(torch.sum(TP))/(float(torch.sum(TP+FP)) + 1e-6)

    return PC
这些只有第一个acc能够正常显示

**Comment by WAMAWAMA** [comment]
你好你好，抱歉这么晚才回复
详情可以参考#8，这个问题是因为torch的版本导致的，可以将计算方式换成基于ndarray的计算方式即可
或者可以忽略训练时候的指标（指标显示有误，但是训练过程是没问题的）

**Comment by sjjdd** [comment]
是的，忽略的话，保存验证集上最高指标模型好像就不行了，一直是0。还有若改成ndarray的意思是指用sklearn中的混淆矩阵来做嘛，这样好像计算速度会很慢吧，我记得是放在cpu上跑的 在2021年03月23日 00:24，Mingyu Wang 写道： 你好你好，抱歉这么晚才回复 详情可以参考#8，这个问题是因为torch的版本导致的，可以将计算方式换成基于ndarray的计算方式即可 或者可以忽略训练时候的指标（指标显示有误，但是训练过程是没问题的） — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by WAMAWAMA** [comment]
@sjjdd 
你好你好，我指的是把tensor转换为数组，之后计算指标即可，可以参考下面的代码
```python


import numpy as np





def get_accuracy(SR,GT,threshold=0.5):
    SR = SR.view(-1)
    GT = GT.view(-1)

    SR = SR.data.cpu().numpy()
    GT = GT.data.cpu().numpy()

    SR = SR > threshold
    GT = GT == np.max(GT)
    corr = np.sum(SR==GT)

    acc = float(corr)/float(SR.shape[0])

    return acc

def get_sensitivity(SR,GT,threshold=0.5):
    SR = SR.view(-1)
    GT = GT.view(-1)

    SR = SR.data.cpu().numpy()
    GT = GT.data.cpu().numpy()

    SR = (SR > threshold).astype(np.float)
    GT = (GT == np.max(GT)).astype(np.float)

    # TP : True Positive
    # FN : False Negative
    TP = (((SR == 1.).astype(np.float) + (GT == 1.).astype(np.float)) == 2.).astype(np.float)
    FN = (((SR == 0.).astype(np.float) + (GT == 1.).astype(np.float)) == 2.).astype(np.float)

    SE = float(np.sum(TP)) / (float(np.sum(TP + FN)) + 1e-6)

    return SE

def get_specificity(SR,GT,threshold=0.5):
    SR = SR.view(-1)
    GT = GT.view(-1)

    SR = SR.data.cpu().numpy()
    GT = GT.data.cpu().numpy()

    SR = (SR > threshold).astype(np.float)
    GT = (GT == np.max(GT)).astype(np.float)

    # TN : True Negative
    # FP : False Positive
    TN = (((SR == 0.).astype(np.float) + (GT == 0.).astype(np.float)) == 2.).astype(np.float)
    FP = (((SR == 1.).astype(np.float) + (GT == 0.).astype(np.float)) == 2.).astype(np.float)

    SP = float(np.sum(TN)) / (float(np.sum(TN + FP)) + 1e-6)

    return SP

def get_DC(SR,GT,threshold=0.5):
    # DC : Dice Coefficient
    SR = SR.view(-1)
    GT = GT.view(-1)

    SR = SR.data.cpu().numpy()
    GT = GT.data.cpu().numpy()


    SR = (SR > threshold).astype(np.float)
    GT = (GT == np.max(GT)).astype(np.float)

    Inter = np.sum(((SR+GT)==2).astype(np.float))
    DC = float(2*Inter)/(float(np.sum(SR)+np.sum(GT)) + 1e-6)

    return DC
```

**Comment by sjjdd** [comment]
好的,多谢多谢
