### ISSUE TITLE
关于数据预处理

### ISSUE THREAD

**Issue by sjjdd** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#15]
使用基于阈值的数据预处理删除TNSCUI的冗余信息部分的时候发现对于大多数图片无效。这是因为阈值的原因吧，就是TNSCUI数据集不是大部分是已经删除了冗余信息，还有少部分含有冗余信息，再使用您的代码好像这些部分含有冗余信息的图片还是没有删除冗余信息啊。期待您的回复！

**Comment by WAMAWAMA** [comment]
你好你好。所谓的去除冗余信息，其实只是通过简单的阈值法去掉厂商logo、标尺、黑边这些区域（整体pipeline图片中那样）。代码中默认设置的阈值应该是没有问题的，你可以着重观察那些有黑边和厂商logo的图像在预处理前后的变化。

**Comment by sjjdd** [comment]
谢谢您，我看有些图片本身那个背景冗余部分和前景部分的差别就不大，就是貌似蒙上了一层雾，这些就去除不了。

**Comment by WAMAWAMA** [comment]
你好你好，你说的类似蒙上一层雾这种情况是比较复杂的噪声，不在我们这份代码的考虑内，抱歉🤝
但是如果你想让模型也可以处理此类噪声图片，可以尝试使用一些扩增手段在其他图片添加噪声，达到增多“有雾”噪声图片的目的，训练集包含越多的这种噪声样本，最后模型一般也会具有处理此类样本的能力
