### ISSUE TITLE
DDTI数据集的处理

### ISSUE THREAD

**Issue by sjjdd** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#16]
你好，请问关于将DDTI数据集中根据xml中的坐标画出结节mask那个黑白图的代码，您有吗，想请教一下，不胜感激。

**Comment by sjjdd** [comment]
就是将DDTI数据集处理成跟TN-SCUI格式的那部分代码能否提供一下呀，想学习一下，但是自己又不会写，若能提供将不胜感激，因为最近在做这个课题。

**Comment by sjjdd** [comment]
您好，请问关于DDTI数据集的处理代码请问您有吗，非常感谢！

**Comment by WAMAWAMA** [comment]
[pre_processing_matlab_4extral.zip](https://github.com/WAMAWAMA/TNSCUI2020-Seg-Rank1st/files/6264904/pre_processing_matlab_4extral.zip)
抱歉抱歉，找了比较久，代码已经打包好了，从step1运行到step4即可完成对DDTI原始数据的预处理

**Comment by sjjdd** [comment]
麻烦您了，多谢大佬
