### ISSUE TITLE
请问关于该竞赛的良恶性分类你们有做吗？

### ISSUE THREAD

**Issue by sjjdd** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#19]
你好，请问你们有做该竞赛的良恶性分类吗？

**Comment by WAMAWAMA** [comment]
有的，当时在1st released 验证机过拟合了，在最后final released的性能降低了一些，所以具体细节和代码就不公开了

**Comment by sjjdd** [comment]
你们的思路是怎样的哇能透露吗，你们是分割和分类分开做的吧，没有联合训练吗？

**Comment by WAMAWAMA** [comment]
我们的思路很简单的，使用resnest+cam注意力机制（用mask监督），所以也算是联合训练。但是联合训练分割性能会掉，所以相当于我们最终：1）分割单独训练，2）分类任务使用分割任务所谓辅助任务。基本和第一名方案（分割同时分类，也是用的smp这个库直接实现的）差不多，不过第一名最终F1要高很多。

**Comment by BelieferQAQ** [comment]
> 你好，请问你们有做该竞赛的良恶性分类吗？

兄弟，你也在做分类吗，可以加个QQ交流下吗? 318831418

**Comment by BelieferQAQ** [comment]
> 

请问下可以参考下您的代码吗，十分感谢！318831418@qq.com


>

**Comment by BelieferQAQ** [comment]
> 我们的思路很简单的，使用resnest+cam注意力机制（用mask监督），所以也算是联合训练。但是联合训练分割性能会掉，所以相当于我们最终：1）分割单独训练，2）分类任务使用分割任务所谓辅助任务。基本和第一名方案（分割同时分类，也是用的smp这个库直接实现的）差不多，不过第一名最终F1要高很多。

请问下可以参考下您的代码吗，十分感谢！[318831418@qq.com](mailto:318831418@qq.com)
