### ISSUE TITLE
关于实验过程中的问题

### ISSUE THREAD

**Issue by Limao0820** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#20]
你好，请问我在按照自述文件配置完的情况下尝试运行第一个网络，然后运行的结果中除了ACC之外，SE，SP，IoU等全部为零，这样的结果是正常的吗？还是说有哪些地方我没有注意到，希望您在百忙中能帮忙回答解决一下，谢谢。

**Comment by zsz1997** [comment]
您好，想请问一下：您所列出的DDTI结果也是基于该数据集进行独立五折交叉验证的训练测试流程得到的吗？训练过程中有没有用到挑战赛的数据呢？
