### ISSUE TITLE
关于step3执行过程中的问题

### ISSUE THREAD

**Issue by Limao0820** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#21]
你好，我翻看之前您回答的问题已经解决了指标显示异常的问题，但是在执行step3进行预测的时候出现了错误，一直没有解决，由于是新手，希望您有时间能帮忙看一下我这个应该是哪里出了问题，谢谢。
![屏幕截图 2021-05-13 153633](https://user-images.githubusercontent.com/70272183/118096206-a02ae780-b403-11eb-93f6-3e547b96f65b.png)

**Comment by WAMAWAMA** [comment]
建议更换skimage的版本，这种问题一般就是库的版本不对

**Comment by Limao0820** [comment]
好的谢谢，请问您运行这个程序的时候用的是哪个版本的？我的版本是0.18.1

**Comment by WAMAWAMA** [comment]
我的是0.15.0哦

**Comment by hammadyounas2008** [comment]
What about sklearn version?
