### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'D:\\TNSCUI2020-Seg-Rank1st-master\\DDTI\\1_or_data\\image\\20155'

### ISSUE THREAD

**Issue by DDxk369** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#26]
大神您好，
       当我在跑step2时出现了这样的报错“ValueError: invalid literal for int() with base 10: 'D:\\TNSCUI2020-Seg-Rank1st-master\\DDTI\\1_or_data\\image\\20155'”

train bs size torch.Size([10, 1, 256, 256])
 |█████████████████████████████████████████████████-| 98.0%  batch_total_loss:0.8571638  lovz_loss:1.3810241  bi_BCE_loss:0.62739336  dice_loss:0.8571638 1e-12
train bs size torch.Size([10, 1, 256, 256])
 |██████████████████████████████████████████████████| 100.0%  batch_total_loss:0.83332884  lovz_loss:1.3876538  bi_BCE_loss:0.6468584  dice_loss:0.83332884 
per epoch training cost Time 00 h:13 m:55 s
Epoch [1/40], Loss: 0.8418
1e-12
@,,@   testing with TTA
Traceback (most recent call last):
  File "D:/TNSCUI2020-Seg-Rank1st-master/step2to4_train_validate_inference/step2_TrainAndValidate.py", line 188, in <module>
    main(config)
  File "D:/TNSCUI2020-Seg-Rank1st-master/step2to4_train_validate_inference/step2_TrainAndValidate.py", line 114, in main
    solver.train()
  File "D:\TNSCUI2020-Seg-Rank1st-master\step2to4_train_validate_inference\tnscui_utils\solver.py", line 355, in train
    acc, SE, SP, PC, DC, IOU= self.test_tta(mode='valid')
  File "D:\TNSCUI2020-Seg-Rank1st-master\step2to4_train_validate_inference\tnscui_utils\solver.py", line 565, in test_tta
    tmp_index = int(tmp_index.split('.')[0][:])
ValueError: invalid literal for int() with base 10: 'D:\\TNSCUI2020-Seg-Rank1st-master\\DDTI\\1_or_data\\image\\20155'

请问这个问题该怎么解决呢？

**Comment by WAMAWAMA** [comment]
是tmp_index = int(tmp_index.split('.')[0][:])这一句
因为我原始的路径，正好int()里面的东西是20155这种，可以转换为int
你的路径和我的不一样，int里面的东西是 'D:\TNSCUI2020-Seg-Rank1st-master\DDTI\1_or_data\image\20155' 这一大坨
改一下代码就好了，比如
把
tmp_index = int(tmp_index.split('.')[0][:])
换成
tmp_str_ = (tmp_index.split('.')[0][:])
tmp_index = int(tmp_str_ .split(sep)[-1])

**Comment by DDxk369** [comment]
哇 谢谢您这么及时耐心的回复，我没想到这么快就回我了 谢谢
