### ISSUE TITLE
关于step1中使用自己数据集的问题

### ISSUE THREAD

**Issue by 775397252** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#28]
csv中数据如下：
![截图_20215302105359](https://user-images.githubusercontent.com/7972945/131866564-1b7eaf29-4d96-4e0f-857d-99dc5effe350.png)
当我运行step1_preprocessing.m文件报错：
![截图_20215502105521](https://user-images.githubusercontent.com/7972945/131866749-a7b9ba5f-3b03-48bc-8415-6599cfdb4662.png)
运行到第二条数据没有gt框的数据报错，第一条有mask是正常的
请问使用自定义数据集有什么注意的吗？

**Comment by WAMAWAMA** [comment]
1）如果某些数据没有对应的GT的话，你可以做一个空图GT，来保证预处理正常进行
2）没有GT的数据，全监督也不能用来训练，如果你单纯想测试，可以先不管这些无GT的数据，最后step3进行推理的时候会自动预处理的
3）自定义数据集可以参考demo 数据集-DDTI数据集，没有特殊需要注意的，但是如果命名是非数字的，那么就需要参考这个issue👉 #27

**Comment by 775397252** [comment]
谢谢你的回复。
源数据本身是有全黑空图GT，但是运行就会报错。
![截图_20211402111409](https://user-images.githubusercontent.com/7972945/131870128-29a3dba0-6af1-41f8-a412-40a1fbc2e86b.png)
我仔细对比了和DDTI数据集差异，只是数据像素不一样，DDTI是560*360，我是256*256

**Comment by 775397252** [comment]
我猜测可能是对于没有mask的图片.m文件没有自动判断，需要手动处理哇

**Comment by WAMAWAMA** [comment]
mask图片如果是空，确实会影响预处理（在(这一行代码)[https://github.com/WAMAWAMA/TNSCUI2020-Seg-Rank1st/blob/2ee9f46bf37c9049a6ffcb36408630108eacb007/step1_preprocessing/step1_preprocessing.m#L63])
这个我之前疏忽了
所以不要把无GT的样本的mask赋值空矩阵，可以赋值为全为1，应该就可以了👍
