### ISSUE TITLE
关于图片裁剪

### ISSUE THREAD

**Issue by 775397252** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#29]
感谢作者开源代码，在复现的时候发现了个问题：对于图片裁剪，matlab和python裁剪结果不一致，matlab裁剪貌似对于多个目标更好，python代码对多个目标只会选取一个来裁剪。这种有什么好的解决方法吗？

**Comment by 775397252** [comment]
![截图_20214316054327](https://user-images.githubusercontent.com/7972945/133589929-d1311fa2-868c-4eb5-a87b-5524ee8aca17.png)
临时注释改行代码

**Comment by WAMAWAMA** [comment]
您说的对，直接注释即可，已经会抢答了👍
