### ISSUE TITLE
关于DDTI数据的问题

### ISSUE THREAD

**Issue by zsz1997** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#30]
您好，想请问一下：您所列出的DDTI结果也是基于该数据集进行独立五折交叉验证的训练测试流程得到的吗？训练过程中有没有用到挑战赛的数据呢？

**Comment by WAMAWAMA** [comment]
没有用到其他数据，是单独只使用DDTI数据集五折交叉验证得到的结果
