### ISSUE TITLE
请问如何解决决这一AssertionError

### ISSUE THREAD

**Issue by xwf12345678** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#31]
File "/content/drive/Shareddrives/wufeixie111@gmail.com/TNSCUI2020-Seg-Rank1st/step2to4_train_validate_inference/loader/data_loader.py", line 281, in __getitem__
    [image, GT] = data_aug(image, GT)
  File "/content/drive/Shareddrives/wufeixie111@gmail.com/TNSCUI2020-Seg-Rank1st/step2to4_train_validate_inference/loader/img_mask_aug.py", line 117, in data_aug
    images_aug = seq_det.augment_images(imgs)  # 进行增强
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/meta.py", line 542, in augment_images
    "got shape %s." % (images.shape,))
  File "/usr/local/lib/python3.7/dist-packages/imgaug/imgaug.py", line 1869, in do_assert
    raise AssertionError(str(message))
AssertionError: Expected 3d/4d array of form (N, height, width) or (N, height, width, channels), got shape (256, 256).

**Comment by WAMAWAMA** [comment]
1）如果你用的是我们提供的数据（比如DDTI数据），那么这个就是imgaug版本问题，多试几个imgaug库的版本即可~
2）或者改一下代码，把images_aug = seq_det.augment_images(imgs) 这里的imgs提前用 np.expand_dims(imgs, 0)扩增一下维度，扩增后再把images_aug 的第一个维度np.squeeze掉就可以了👍

**Comment by xwf12345678** [comment]
那请问你们当时所使用的imgaug版本是多少呢？

**Comment by WAMAWAMA** [comment]
当时的找不到了，不过现在用的如下👇
Package                            Version    
---------------------------------- -----------
alabaster                          0.7.12     
anaconda-client                    1.7.2      
anaconda-navigator                 1.9.7      
anaconda-project                   0.8.3      
antspyx                            0.2.7      
asn1crypto                         1.0.1      
astroid                            2.3.1      
astropy                            3.2.2      
atomicwrites                       1.3.0      
attrs                              19.2.0     
Babel                              2.7.0      
backcall                           0.1.0      
backports.functools-lru-cache      1.5        
backports.os                       0.1.1      
backports.shutil-get-terminal-size 1.0.0      
backports.tempfile                 1.0        
backports.weakref                  1.0.post1  
batchgenerators                    0.21       
beautifulsoup4                     4.8.0      
bitarray                           1.0.1      
bkcharts                           0.2        
bleach                             3.1.0      
bokeh                              1.3.4      
boto                               2.49.0     
Bottleneck                         1.2.1      
certifi                            2019.9.11  
cffi                               1.12.3     
chardet                            3.0.4      
chart-studio                       1.1.0      
Click                              7.0        
cloudpickle                        1.2.2      
clyent                             1.2.2      
colorama                           0.4.1      
conda                              4.9.0      
conda-build                        3.18.9     
conda-package-handling             1.6.0      
conda-verify                       3.4.2      
contextlib2                        0.6.0      
cryptography                       2.7        
cycler                             0.10.0     
Cython                             0.29.13    
cytoolz                            0.10.0     
dask                               2.5.2      
decorator                          4.4.0      
defusedxml                         0.6.0      
dicom2nifti                        2.3.0      
distributed                        2.5.2      
docutils                           0.15.2     
efficientnet-pytorch               0.6.3      
einops                             0.3.0      
entrypoints                        0.3        
et-xmlfile                         1.0.1      
fastcache                          1.1.0      
filelock                           3.0.12     
Flask                              1.1.1      
fsspec                             0.5.2      
future                             0.17.1     
gevent                             1.4.0      
glob2                              0.7        
gmpy2                              2.0.8      
greenlet                           0.4.15     
h5py                               2.9.0      
HeapDict                           1.0.1      
html5lib                           1.0.1      
idna                               2.8        
imageio                            2.6.0      
imagesize                          1.1.0      
imgaug                             0.4.0      
importlib-metadata                 0.23       
ipykernel                          5.1.2      
ipython                            7.8.0      
ipython-genutils                   0.2.0      
ipywidgets                         7.5.1      
isort                              4.3.21     
itsdangerous                       1.1.0      
jdcal                              1.4.1      
jedi                               0.15.1     
jeepney                            0.4.1      
Jinja2                             2.10.3     
joblib                             0.13.2     
json5                              0.8.5      
jsonschema                         3.0.2      
jupyter                            1.0.0      
jupyter-client                     5.3.3      
jupyter-console                    6.0.0      
jupyter-core                       4.5.0      
jupyterlab                         1.1.4      
jupyterlab-server                  1.0.6      
keyring                            18.0.0     
kiwisolver                         1.1.0      
lazy-object-proxy                  1.4.2      
libarchive-c                       2.8        
libtiff                            0.4.2      
lief                               0.9.0      
linecache2                         1.0.0      
llvmlite                           0.29.0     
locket                             0.2.0      
lxml                               4.4.1      
Mako                               1.1.4      
Markdown                           3.3.4      
MarkupSafe                         1.1.1      
matplotlib                         3.1.1      
mccabe                             0.6.1      
medcam                             0.1.6      
MedPy                              0.4.0      
mistune                            0.8.4      
mkl-fft                            1.0.14     
mkl-random                         1.1.0      
mkl-service                        2.3.0      
mock                               3.0.5      
more-itertools                     7.2.0      
mpmath                             1.1.0      
msgpack                            0.6.1      
multipledispatch                   0.6.0      
munch                              2.5.0      
navigator-updater                  0.2.1      
nbconvert                          5.6.0      
nbformat                           4.4.0      
networkx                           2.3        
nibabel                            3.2.1      
nltk                               3.4.5      
nnunet                             1.6.6      
nose                               1.3.7      
notebook                           6.0.1      
numba                              0.45.1     
numexpr                            2.7.0      
numpy                              1.21.2     
numpydoc                           0.9.1      
olefile                            0.46       
opencv-python                      4.0.0.21   
openpyxl                           3.0.0      
packaging                          19.2       
pandas                             0.25.1     
pandocfilters                      1.4.2      
parso                              0.5.1      
partd                              1.0.0      
path.py                            12.0.1     
pathlib2                           2.3.5      
patsy                              0.5.1      
pep8                               1.7.1      
pexpect                            4.7.0      
pickleshare                        0.7.5      
Pillow                             8.3.1      
pip                                19.2.3     
pkginfo                            1.5.0.1    
plotly                             4.14.3     
pluggy                             0.13.0     
ply                                3.11       
pretrainedmodels                   0.7.4      
prettytable                        2.4.0      
prometheus-client                  0.7.1      
prompt-toolkit                     2.0.10     
protobuf                           3.15.6     
psutil                             5.6.3      
ptyprocess                         0.6.0      
py                                 1.8.0      
pycodestyle                        2.5.0      
pycosat                            0.6.3      
pycparser                          2.19       
pycrypto                           2.6.1      
pycurl                             7.43.0.3   
pydicom                            2.2.1      
pyflakes                           2.1.1      
Pygments                           2.4.2      
pylint                             2.4.2      
pymrmr                             0.1.11     
pyodbc                             4.0.27     
pyOpenSSL                          19.0.0     
pyparsing                          2.4.2      
pyrsistent                         0.15.4     
PySide2                            5.15.2     
PySocks                            1.7.1      
pytest                             5.2.1      
pytest-arraydiff                   0.3        
pytest-astropy                     0.5.0      
pytest-doctestplus                 0.4.0      
pytest-openfiles                   0.4.0      
pytest-remotedata                  0.3.2      
python-dateutil                    2.8.0      
pytz                               2019.3     
PyWavelets                         1.0.3      
PyYAML                             5.1.2      
pyzmq                              18.1.0     
QtAwesome                          0.6.0      
qtconsole                          4.5.5      
QtPy                               1.9.0      
requests                           2.22.0     
retrying                           1.3.3      
rope                               0.14.0     
ruamel-yaml                        0.15.46    
scikit-image                       0.15.0     
scikit-learn                       0.23.0     
scipy                              1.3.1      
seaborn                            0.9.0      
SecretStorage                      3.1.1      
segmentation-models-pytorch        0.1.2      
Send2Trash                         1.5.0      
setuptools                         41.4.0     
Shapely                            1.7.1      
shiboken2                          5.15.2     
simplegeneric                      0.8.1      
SimpleITK                          1.2.4      
singledispatch                     3.4.0.3    
six                                1.12.0     
sklearn                            0.0        
snowballstemmer                    2.0.0      
sortedcollections                  1.1.2      
sortedcontainers                   2.1.0      
soupsieve                          1.9.3      
Sphinx                             2.2.0      
sphinxcontrib-applehelp            1.0.1      
sphinxcontrib-devhelp              1.0.1      
sphinxcontrib-htmlhelp             1.0.2      
sphinxcontrib-jsmath               1.0.1      
sphinxcontrib-qthelp               1.0.2      
sphinxcontrib-serializinghtml      1.1.3      
sphinxcontrib-websupport           1.1.2      
spyder                             3.3.6      
spyder-kernels                     0.5.2      
SQLAlchemy                         1.3.9      
statsmodels                        0.10.1     
sympy                              1.4        
tables                             3.5.2      
tblib                              1.4.0      
tensorboardX                       2.1        
terminado                          0.8.2      
testpath                           0.4.2      
threadpoolctl                      2.1.0      
tifffile                           2021.8.8   
timm                               0.2.1      
toolz                              0.10.0     
torch                              1.6.0+cu101
torchvision                        0.7.0+cu101
tornado                            6.0.3      
tqdm                               4.36.1     
traceback2                         1.4.0      
traitlets                          4.3.3      
ttach                              0.0.3      
unicodecsv                         0.14.1     
unittest2                          1.1.0      
urllib3                            1.24.2     
wcwidth                            0.1.7      
webcolors                          1.11.1     
webencodings                       0.5.1      
Werkzeug                           0.16.0     
wheel                              0.33.6     
widgetsnbextension                 3.5.1      
wrapt                              1.11.2     
wurlitzer                          1.0.3      
xlrd                               1.2.0      
XlsxWriter                         1.2.1      
xlwt                               1.3.0      
zict                               1.0.0      
zipp                               0.6.0
