### ISSUE TITLE
第一阶段训练时候的问题

### ISSUE THREAD

**Issue by BelieferQAQ** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#33]
大神您好，我有些疑问，麻烦您回答下，

第一个问题，readme中，脚本中设置参数：
parser.add_argument('--filepath_img', type=str, default='./DDTI/2_preprocessed_data/stage1/p_image')
parser.add_argument('--filepath_mask', type=str, default='./DDTI/2_preprocessed_data/stage1/p_image')
请问下，第二个参数：--filepath_mask，对应的路径不应该是p_mask文件吗?

第二个问题，为什么我在训练第一阶段时，验证集的指标除了ACC都是0呢（每一个epoch都是）？IOU也是0
Epoch [23/405], Loss: 0.2362
9.948524919112924e-05
@,,@   testing with TTA
[Validation] Acc: 0.9521, SE: 0.0000, SP: 0.0000, PC: 0.0000, Dice: 0.0000, IOU: 0.0000
per epoch testing&vlidation cost Time 00 h:00 m:07 s

第三个问题，第二阶段的所需要的数据集，是怎么获得的，依靠的哪句代码？
torchvision.utils.save_image(images_all.data.cpu(), os.path.join(self.result_path, 'images', '%s_%d_image.png' (mode, i))， nrow=self.batch_size)
是这句吗?并没有发现保存mask到stage2文件夹目录下

打扰了，十分感谢！

**Comment by WAMAWAMA** [comment]
你好你好

1）第一个问题：抱歉，```filepath_mask```这个参数确实是p_mask，我搞错了，感谢纠正；
2）第二个问题：这个问题大概率是库的问题，参考这几个解决方案即可： #8，#2，#14（推荐先看14）;
3）第三个问题：这个是由matlab代码生成的，但是这个repo里的[step3_TestOrInference.py](https://github.com/WAMAWAMA/TNSCUI2020-Seg-Rank1st/blob/7cb9eeb8ba61ad9583ba9bcd13f3ab00b8d7b44a/step2to4_train_validate_inference/step3_TestOrInference.py#L64)也有对应的python实现，就是那个[preprocess](https://github.com/WAMAWAMA/TNSCUI2020-Seg-Rank1st/blob/7cb9eeb8ba61ad9583ba9bcd13f3ab00b8d7b44a/step2to4_train_validate_inference/step3_TestOrInference.py#L64)函数，你可以参考这个函数自己制作训练stage2的数据。

**Comment by BelieferQAQ** [comment]
感谢您的回答。另外请问 category.csv和train.csv文件中结节的类别，都是记录原始数据集（TNSCUI2020）中的吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WAMAWAMA/TNSCUI2020-Seg-Rank1st"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上9:08
***@***.***&gt;;
抄送:&nbsp;"ambition for ***@***.******@***.***&gt;;
主题:&nbsp;Re: [WAMAWAMA/TNSCUI2020-Seg-Rank1st] 第一阶段训练时候的问题 (Issue #33)





 
你好你好
 
1）第一个问题：抱歉，filepath_mask这个参数确实是p_mask，我搞错了，感谢纠正；
 2）第二个问题：这个问题大概率是库的问题，参考这几个解决方案即可： #8，#2，#14（推荐先看14）;
 3）第三个问题：这个是由matlab代码生成的，但是这个repo里的step3_TestOrInference.py也有对应的python实现，就是那个preprocess函数，你可以参考这个函数自己制作训练stage2的数据。

**Comment by WAMAWAMA** [comment]
> 感谢您的回答。另外请问 category.csv和train.csv文件中结节的类别，都是记录原始数据集（TNSCUI2020）中的吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "WAMAWAMA/TNSCUI2020-Seg-Rank1st" ***@***.***&gt;; 发送时间:&nbsp;2022年4月28日(星期四) 晚上9:08 ***@***.***&gt;; 抄送:&nbsp;"ambition for ***@***.******@***.***&gt;; 主题:&nbsp;Re: [WAMAWAMA/TNSCUI2020-Seg-Rank1st] 第一阶段训练时候的问题 (Issue #33) 你好你好 1）第一个问题：抱歉，filepath_mask这个参数确实是p_mask，我搞错了，感谢纠正； 2）第二个问题：这个问题大概率是库的问题，参考这几个解决方案即可： #8，#2，#14（推荐先看14）; 3）第三个问题：这个是由matlab代码生成的，但是这个repo里的step3_TestOrInference.py也有对应的python实现，就是那个preprocess函数，你可以参考这个函数自己制作训练stage2的数据。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt; 


不是的哦，是随机生成的，详见DDTI.zip的readme ![image](https://user-images.githubusercontent.com/41294317/165794646-56c3f224-42a0-4d8c-b7ae-10cdac3769c0.png)

**Comment by BelieferQAQ** [comment]
十分感谢。另外我想请问一下，那个--Task_name,第一阶段需要改成‘dpv3plus_stage1_’第二阶段需要修改成什么？

**Comment by WAMAWAMA** [comment]
> 十分感谢。另外我想请问一下，那个--Task_name,第一阶段需要改成‘dpv3plus_stage1_’第二阶段需要修改成什么？

这个是自定义的，随意即可，后面运行的脚本设置好你自定义的taskname对应的路径就好b(￣▽￣)d

**Comment by BelieferQAQ** [comment]
感谢！另外，我想请问一下，
1.因为我没有该代码数据集原始数据，所以我想知道预处理之后，图片发生了什么变化。我看评论好像是去除了什么水印类似的。
2.我准备使用我自己的数据集（甲状腺CT），大小为512*512，图片如下所示，不知道还需要进行预处理吗？
![image](https://user-images.githubusercontent.com/91660759/165897341-3035e373-274e-4b3f-978b-6500244b71f7.png)
3.我的数据集为jpg格式，应该不用特意去改为png格式了吧。只需改下读取图片的代码就可以了吧

**Comment by WAMAWAMA** [comment]
> 感谢！另外，我想请问一下， 1.因为我没有该代码数据集原始数据，所以我想知道预处理之后，图片发生了什么变化。我看评论好像是去除了什么水印类似的。 2.我准备使用我自己的数据集（甲状腺CT），大小为512*512，图片如下所示，不知道还需要进行预处理吗？ ![image](https://user-images.githubusercontent.com/91660759/165897341-3035e373-274e-4b3f-978b-6500244b71f7.png) 3.我的数据集为jpg格式，应该不用特意去改为png格式了吧。只需改下读取图片的代码就可以了吧

1) 你理解的没错，只是去除了图像边框上的水印之类的；
2）是否需要预处理，性能决定，你的部分图像（如26号）有大量的背景，如果是我，我会尝试去除；
3）没错，但是我是吧文件名（带png后缀）放到了csv文件里，你可以根据你的需求修改

**Comment by BelieferQAQ** [comment]
谢谢您的回答，再打扰您一下：
1.step3中是只有单张图片的IOU和DSC吗，没有对整个测试集的整体iou和dsc计算指标对吧。
2.step4中的整合结果，大概是怎么操作？我观察：/media/root/s1_fold51_s2_fold52 ，不太懂代表的含义

**Comment by BelieferQAQ** [comment]
请问下，您的这个test_fold1_DDT1.py程序中



这个xlsh文件在哪里呢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WAMAWAMA/TNSCUI2020-Seg-Rank1st"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月29日(星期五) 下午3:32
***@***.***&gt;;
抄送:&nbsp;"ambition for ***@***.******@***.***&gt;;
主题:&nbsp;Re: [WAMAWAMA/TNSCUI2020-Seg-Rank1st] 第一阶段训练时候的问题 (Issue #33)





  
感谢！另外，我想请问一下， 1.因为我没有该代码数据集原始数据，所以我想知道预处理之后，图片发生了什么变化。我看评论好像是去除了什么水印类似的。 2.我准备使用我自己的数据集（甲状腺CT），大小为512*512，图片如下所示，不知道还需要进行预处理吗？  3.我的数据集为jpg格式，应该不用特意去改为png格式了吧。只需改下读取图片的代码就可以了吧
   
你理解的没错，只是去除了图像边框上的水印之类的；
 2）是否需要预处理，性能决定，你的部分图像（如26号）有大量的背景，如果是我，我会尝试去除；
 3）没错，但是我是吧文件名（带png后缀）放到了csv文件里，你可以根据你的需求修改
