### ISSUE TITLE
使用自己数据集时报错

### ISSUE THREAD

**Issue by Llululu** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#34]
RuntimeError: Given groups=1, weight of size [56, 1, 3, 3], expected input[16, 3, 257, 257] to have 1 channels, but got 3 channels instead

**Comment by WAMAWAMA** [comment]
输入图像是RGB三通道的吧，把config对应的地方改成3即可（👉[这里,训练代码的135行 ``img_ch`` 这个参数](https://github.com/WAMAWAMA/TNSCUI2020-Seg-Rank1st/blob/0e03aead2f27f280465ee855b64790b07a0e05cc/step2to4_train_validate_inference/step2_TrainAndValidate.py#L135)）

**Comment by Llululu** [comment]
哦哦好的我试试

**Comment by Llululu** [comment]
我的mask也是三通道的，是不是out_ch也要改成3呢

**Comment by Llululu** [comment]
嗯嗯，我还是转成一通道了
