### ISSUE TITLE
请问分类的任务是如何进行的？

### ISSUE THREAD

**Issue by UCPRER** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#37]
你好！我看到比赛的评估指标中也包含分类任务，想请教您能否分享一下这个比赛中进行分类任务的方法呢？

**Comment by WAMAWAMA** [comment]
当时我们用resnest直接做的分类，训练和测试的策略和分割类似（交叉验证，扩增，tta）

**Comment by UCPRER** [comment]
谢谢🙏
