### ISSUE TITLE
请问图片预处理时x_hold_range计算中的数值是怎么得到的？

### ISSUE THREAD

**Issue by UCPRER** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#38]
https://github.com/WAMAWAMA/TNSCUI2020-Seg-Rank1st/blob/0e03aead2f27f280465ee855b64790b07a0e05cc/step2to4_train_validate_inference/tnscui_utils/TNSCUI_preprocess.py#L27-L28

你好，关于上面代码中的0.24 / 3, 2.2 / 3，0.8 / 3, 1.8 / 3这几个数值，我理解的是这四个值表示行方向和列方向中不能被裁切的范围，但是不太明白为什么要设定这个范围，以及这个范围是怎么计算得到的。如果我要用其他的数据集，要修改这些值吗？

**Comment by WAMAWAMA** [comment]
你理解的没错，就是“预处理过程”中不能被裁切掉的范围
之所以设定这个，是因为我们去掉背景用的是“简单的阈值法去掉低信号区域”，但是一些nodule是囊性的（很暗），如果不设定这个范围的话就会把这种结节也crop掉

不过，我们后面实验发现，其实不需要“预处理”来crop掉所谓的背景，性能甚至更高
所以我建议你可以修改代码，去掉crop这一步

**Comment by UCPRER** [comment]
谢谢解答🙏
