### ISSUE TITLE
您好，我在运行step1_prerocessing.m时。发生了如下错误：未定义与 'cell' 类型的输入参数相对应的函数 'string'。

### ISSUE THREAD

**Issue by sktyut** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#4]
您好，我在运行step1_prerocessing.m时。发生了如下错误：

未定义与 'cell' 类型的输入参数相对应的函数 'string'。

出错 step1_preprocessing (line 33)
fprintf(fid,'%s,%s,%s\n',string(strrr));

**Comment by WAMAWAMA** [comment]
你好你好，这个可能是因为我是2018a的问题，matlab2018a的话，这个操作是妹有任何问题的，如果你是其他版本，可以修改代码如下
```matlab
fid=fopen('qwe.csv','w');
strrr=['ID','CATE','size'];
fprintf(fid,'%s,%s,%s\n','ID','CATE','size');
fclose(fid);
```
