### ISSUE TITLE
数据处理问题

### ISSUE THREAD

**Issue by kurie21** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#41]
您好，您提到“在预处理后大小为256x256像素的图像中，首先得到结节感兴趣区域的最小外平方，然后若正方形边长n大于80，则外扩m为20，否则m为30。”，请问这里的80、20、30这三个数据是否有理论依据呢？还是您这边通过实验得到的经验值呢？

**Comment by WAMAWAMA** [comment]
您好，这些是通过实验得到的经验值

**Comment by kurie21** [comment]
好的，感谢您的解答！
