### ISSUE TITLE
训练过程中日志打印出来的SE,PC,Dice IOU一直输出位0 训练结束后vaid文件夹中dice 与iou也为0

### ISSUE THREAD

**Issue by apuomline** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#42]
我尝试寻找了原因，由于 get_sensitivity函数内部使用GT = GT == torch.max(GT) 作为分类阈值，后面 TP = ((SR==1)+(GT==1))==2
(SR==1)与(GT==1)同时满足的组合个数为0 FN的计算也为0。由于TP,FN计算得到为0导致最后计算出来的SE,PC,Dice,IOU值为0

**Comment by WAMAWAMA** [comment]
你好，可以参考issue #14

**Comment by apuomline** [comment]
好的，感谢您抽时间回复我的问题。按照您的解答，问题已经解决了。再次感谢您！！！
