### ISSUE TITLE
augmentation_prob

### ISSUE THREAD

**Issue by hitxujian** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#5]
is you set augmentation_prob=1,this mean every train sample all do data augument? 请问对所有的训练数据都做了增强，这样不就丢失了原始训练数据吗？

**Comment by WAMAWAMA** [comment]
您好，
（1）实际上我们使用的数据增广策略（详见[/step2to4_train_validate_inference/loader/img_mask_aug.py](https://github.com/WAMAWAMA/TNSCUI2020-Seg-Rank1st/blob/master/step2to4_train_validate_inference/loader/img_mask_aug.py)）中，有额外设置增广的概率，故实际扩增概率并不等于1；
（2）此外，我个人认为适当的数据增广并不会丢失原始数据信息，例如在增广程度很小（旋转几度）时，可以认为增广数据与原始数据近似一致，故并不会存在'丢失原始数据的问题'
（3）我们并未进行有关数据增广策略的对比实验，但的确可能出现'保持固定比例训练数据为原始数据会获得更大增益'的情况，您可自行尝试👍

**Comment by hitxujian** [comment]
对于DDTI数据集，我按照4：1划分训练和验证，发现关闭数据增广，验证集效果比较好（好很多）。请问这个现象您有发现过吗，可能的原因是什么？

**Comment by WAMAWAMA** [comment]
您好，我们对数据增广策略的尝试主要是基于TN-SCUI比赛数据集的，故此套增广策略可能并不适合DDTI数据。
此外，不同数据增广策略会导致不同的TTA收益，您可自行尝试使用不同的增广策略并观察使用或不使用TTA的差异。
（最近暂时没有时间做这部分的相关实验，请见谅，后续有时间会观察下这个细节）
