### ISSUE TITLE
About IOU

### ISSUE THREAD

**Issue by Desperado721** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#8]
Hi,
Thanks for sharing code!W
我想用已有的model作为预训练的模型，然后继续用自己的数据训练，但为了先验证模型的正确性，我在DDTI先做了fine-tune, 可IOU, SE, SP等指标都为0 , 理论上不fine-tine, 这几个值都不应该为0的， 我使用的是step2的脚本，我发现网络train出来的结果非常小，达不到0.5的阈值，想问下是什么原因呢？谢谢

![image](https://user-images.githubusercontent.com/42107292/97258986-1c573800-17f0-11eb-9069-8c00a1fa9a01.png)

**Comment by WAMAWAMA** [comment]
您好，
1）可以查看 #2 这个issue里面提及的colab脚本，使用预权重进行推理，得到的概率图值不应该很小才对
2）看起来，似乎你print了预测概率值和gt，但是gt都为0.0039，但是实际上应该为很多0和1才对，建议可视化一下网络预测的图片和GT，看一下到底是什么情况

**Comment by lovelyyutian** [comment]
我也遇到了，loss正常下降，acc正常上升，最后得到模型用测试脚本测试时可以得到IOU指标。这个问题应该是pytorch版本的问题，后面修改了训练阶段计算IOU，DICE指标的代码就正常了

**Comment by WAMAWAMA** [comment]
@lovelyyutian 我想起来了，我同伴在跑step2脚本的时候，torch版本是1.3，计算指标时也出现了问题，他自己改为转换成numpy计算指标就解决了

@Desperado721 可以尝试将[step3_TestOrInference.py](https://github.com/WAMAWAMA/TNSCUI2020-Seg-Rank1st/blob/master/step2to4_train_validate_inference/step3_TestOrInference.py)里面计算dice和iou的函数，替换掉step2脚本中使用到的指标计算函数

**Comment by Desperado721** [comment]
谢谢回复，重新放在numpy上以后指标是正常了，应该是torch的问题，还有，发现readme上的一个小错误，
python step2_TrainAndValidate.py \
--batch_size=3 \
--Task_name='dpv3plus_stage1_'\
--csv_file='./DDTI/2_preprocessed_data/train.csv' \
--filepath_img='./DDTI/2_preprocessed_data/stage1/p_image' \
-**_-filepath_mask='./DDTI/2_preprocessed_data/stage1/p_image' \_**
--fold_idx=1

这个地方应该是p_mask哦,  我第一次直接复制过来没有仔细看，所以GT有问题，谢谢回复～

**Comment by Desperado721** [comment]
> 我也遇到了，loss正常下降，acc正常上升，最后得到模型用测试脚本测试时可以得到IOU指标。这个问题应该是pytorch版本的问题，后面修改了训练阶段计算IOU，DICE指标的代码就正常了

谢谢回复，已正常

**Comment by Desperado721** [comment]
> @lovelyyutian 3Q3Q，我想起来了，我们组员在跑step2脚本的时候，torch版本是1.3，计算指标时也出现了问题，他自己改为转换成numpy计算指标就解决了
> 
> @Desperado721 可以尝试用[step3_TestOrInference.py](https://github.com/WAMAWAMA/TNSCUI2020-Seg-Rank1st/blob/master/step2to4_train_validate_inference/step3_TestOrInference.py)里面计算dice和iou的函数，替换掉step2脚本中使用到的指标计算函数

谢谢回复，重新放在numpy上以后指标是正常了，应该是torch的问题，还有，发现readme上的一个小错误，
python step2_TrainAndValidate.py
--batch_size=3
--Task_name='dpv3plus_stage1_'
--csv_file='./DDTI/2_preprocessed_data/train.csv'
--filepath_img='./DDTI/2_preprocessed_data/stage1/p_image'
-_-filepath_mask='./DDTI/2_preprocessed_data/stage1/p_image' _
--fold_idx=1

这个地方应该是p_mask哦, 我第一次直接复制过来没有仔细看，所以GT有问题，谢谢回复～
