### ISSUE TITLE
你好，我在自己数据集使用你的方案，级联两个网络后IoU比只用第一个网络还低了？

### ISSUE THREAD

**Issue by lovelyyutian** [WAMAWAMA/TNSCUI2020-Seg-Rank1st#9]
您好，感谢你分享的优秀方案。我在自己数据集上复现时遇到一些问题，想跟您交流下：
数据集：
我使用TNSCUI公开的训练集重新按照8:2划分为训练集(2915)和测试集(729),然后按照你的预处理方法进行处理生成stage1和stage2的数据。
问题：
按照你描述的步骤，采用5折交叉验证，训练完fold_1 后发现stage1网络在验证集上的IoU(0.804),stage2网络单独在验证集上测试I oU(0.85)。级联两个网络一起测试的IoU只有0.776。
我不知道哪里出了问题，按理说级联两个网络结果至少不会比第一个网络差吧？
另外，训练第二个网络时，除了改image和mask路径外，image_size是否也要改成512？

**Comment by WAMAWAMA** [comment]
您好
1）你的训练结果和我是类似的，第一级Iou大概在0.8，第二级基于roi外扩小图训练的Iou大概在0.86
2）训练第二级的尺寸不是固定的，256和512我都尝试过，512训练出来的第二级会比256更好一些，准确的说是级联之后提升会多一点
3）你如果是使用256尺寸图片训练的第二级，那么需要在[step3_TestOrInference.py](https://github.com/WAMAWAMA/TNSCUI2020-Seg-Rank1st/blob/master/step2to4_train_validate_inference/step3_TestOrInference.py)中修改c2_size为256，这个参数对应着训练第二级时候的输入图像的尺寸，如下：
```python

    use_c2_flag = False
    c2_tta = False
    c2_size = 512  # 训练第二级模型时，输入图像的尺寸
    c2_resize_order = 0

```

如果这个参数不对应，那么第二级就很难带来增益

**Comment by lovelyyutian** [comment]
[我训练第二个网络时step2_TrainAndValidate.py中image_size设为512了，级联测试时step3_TestOrInference.py中c2_size对应得也是512，现在找不到问题] @WAMAWAMA

**Comment by WAMAWAMA** [comment]
@lovelyyutian 也就是问题没有解决，级联第二级结果仍然很低是么？
step3的脚本逻辑还是比较简单的，建议一步一步查看哪里出问题
1）img_path是否对应未去除背景的原始图像（去除背景其实也ok）
2）原始图像预处理之后的图片是否有问题，也就是去除背景这一步，输出的图片是否有问题

如果检查了这两个都没问题后，还是有问题，，，那就很诡异了，，

**Comment by lovelyyutian** [comment]
@WAMAWAMA
 1.测试级联网络时使用的是stage1的p_image和p_mask，step3_TestOrInference.py 中fold_flag设为True。
2.运行step3脚本的同时我保存了stage1和stage2的输入输出，都没问题。
最后统计出单独用stage1 IoU大于级联网络的有379张，等于的有6张，小于的有200张(fold_1交叉验证的验证集总共585)，而且绝大部分stage1 > cascade的现象都发生在stage1 IoU本身都挺高的情况下(>0.8)，也就是级联第二个网络后没有达到精修的效果，反而IoU低了一点。
方不方便留个您的邮箱，我把一些可视化的结果发给你，帮我分析下😁

**Comment by WAMAWAMA** [comment]
@lovelyyutian 
我的邮箱 ：wmy19970215@gmail.com
另外：
1）第二级网络是否训练充分，建议训练时间久一些，80个epoch以上
2）是否开启TTA，可能存在使用TTA后第二级才有增益的情况出现

**Comment by lovelyyutian** [comment]
@WAMAWAMA 
1.第二级网络训练了300个epoch左右，最终best_model保存在epoch 87，使用best_model做的测试。
2.step3脚本中c1_tta和c2_tta都设置为True的

**Comment by WAMAWAMA** [comment]
如果你使用p_image测试，那么可以将step3的orimg设置为true，这样就不会进行去除黑边的预处理

**Comment by lovelyyutian** [comment]
@WAMAWAMA 嗯嗯，我试了，orimg设为True和False差别不是很大

**Comment by WAMAWAMA** [comment]
我看了一下你发给我的结果，发现第二级分割的不是很准，第一级的定位还算是准确的
我不太确定，但是应该是第二级的原因了，
1）重新训练下第二级看看
2）第二级换成256尺寸训练试一下

lovelyyutian <notifications@github.com> 于2020年10月30日周五 上午11:34写道：

**Comment by lovelyyutian** [comment]
@WAMAWAMA 
应该是dtype的问题，step3脚本里第254行
mask_c1_array_biggest[dim1_cut_min:dim1_cut_max, dim2_cut_min:dim2_cut_max] = mask_c2_array
mask_c1_array_biggest为int，mask_c2_array为float，执行完这一步把c2mask放回c1mask后，mask_c2_array的sum()减小了。
统一type后正常

**Comment by WAMAWAMA** [comment]
wow，确实，放回 mask_c1_array_biggest前，将 mask_c1_array_biggest转换为float32是必要的
而且colab在线测试结果不对也是因为这个问题，感谢感谢👍

可以的话，麻烦你pull request一下这个修改，这样方便我在issue里引用

lovelyyutian <notifications@github.com> 于2020年10月31日周六 下午11:04写道：

**Comment by WAMAWAMA** [comment]
感谢这位好哥们儿，bug已被修复
@ #10
